//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Longbow_TauseefModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Longbow_TauseefEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Longbow_TauseefEntities object using the connection string found in the 'Longbow_TauseefEntities' section of the application configuration file.
        /// </summary>
        public Longbow_TauseefEntities() : base("name=Longbow_TauseefEntities", "Longbow_TauseefEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Longbow_TauseefEntities object.
        /// </summary>
        public Longbow_TauseefEntities(string connectionString) : base(connectionString, "Longbow_TauseefEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Longbow_TauseefEntities object.
        /// </summary>
        public Longbow_TauseefEntities(EntityConnection connection) : base(connection, "Longbow_TauseefEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Email> Emails
        {
            get
            {
                if ((_Emails == null))
                {
                    _Emails = base.CreateObjectSet<Email>("Emails");
                }
                return _Emails;
            }
        }
        private ObjectSet<Email> _Emails;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Emails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmails(Email email)
        {
            base.AddObject("Emails", email);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Longbow_TauseefModel", Name="Email")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Email : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Email object.
        /// </summary>
        /// <param name="mail_Id">Initial value of the Mail_Id property.</param>
        public static Email CreateEmail(global::System.Int64 mail_Id)
        {
            Email email = new Email();
            email.Mail_Id = mail_Id;
            return email;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Mail_Id
        {
            get
            {
                return _Mail_Id;
            }
            set
            {
                if (_Mail_Id != value)
                {
                    OnMail_IdChanging(value);
                    ReportPropertyChanging("Mail_Id");
                    _Mail_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Mail_Id");
                    OnMail_IdChanged();
                }
            }
        }
        private global::System.Int64 _Mail_Id;
        partial void OnMail_IdChanging(global::System.Int64 value);
        partial void OnMail_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Case_Id
        {
            get
            {
                return _Case_Id;
            }
            set
            {
                OnCase_IdChanging(value);
                ReportPropertyChanging("Case_Id");
                _Case_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Case_Id");
                OnCase_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Case_Id;
        partial void OnCase_IdChanging(Nullable<global::System.Int32> value);
        partial void OnCase_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Entry_Id
        {
            get
            {
                return _Entry_Id;
            }
            set
            {
                OnEntry_IdChanging(value);
                ReportPropertyChanging("Entry_Id");
                _Entry_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Entry_Id");
                OnEntry_IdChanged();
            }
        }
        private global::System.String _Entry_Id;
        partial void OnEntry_IdChanging(global::System.String value);
        partial void OnEntry_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sender
        {
            get
            {
                return _Sender;
            }
            set
            {
                OnSenderChanging(value);
                ReportPropertyChanging("Sender");
                _Sender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sender");
                OnSenderChanged();
            }
        }
        private global::System.String _Sender;
        partial void OnSenderChanging(global::System.String value);
        partial void OnSenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Recipient
        {
            get
            {
                return _Recipient;
            }
            set
            {
                OnRecipientChanging(value);
                ReportPropertyChanging("Recipient");
                _Recipient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Recipient");
                OnRecipientChanged();
            }
        }
        private global::System.String _Recipient;
        partial void OnRecipientChanging(global::System.String value);
        partial void OnRecipientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Sent
        {
            get
            {
                return _Date_Sent;
            }
            set
            {
                OnDate_SentChanging(value);
                ReportPropertyChanging("Date_Sent");
                _Date_Sent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Sent");
                OnDate_SentChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Sent;
        partial void OnDate_SentChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_SentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Recieved
        {
            get
            {
                return _Date_Recieved;
            }
            set
            {
                OnDate_RecievedChanging(value);
                ReportPropertyChanging("Date_Recieved");
                _Date_Recieved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Recieved");
                OnDate_RecievedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Recieved;
        partial void OnDate_RecievedChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_RecievedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Message_Object
        {
            get
            {
                return StructuralObject.GetValidValue(_Message_Object);
            }
            set
            {
                OnMessage_ObjectChanging(value);
                ReportPropertyChanging("Message_Object");
                _Message_Object = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message_Object");
                OnMessage_ObjectChanged();
            }
        }
        private global::System.Byte[] _Message_Object;
        partial void OnMessage_ObjectChanging(global::System.Byte[] value);
        partial void OnMessage_ObjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Attachments
        {
            get
            {
                return _Attachments;
            }
            set
            {
                OnAttachmentsChanging(value);
                ReportPropertyChanging("Attachments");
                _Attachments = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attachments");
                OnAttachmentsChanged();
            }
        }
        private Nullable<global::System.Boolean> _Attachments;
        partial void OnAttachmentsChanging(Nullable<global::System.Boolean> value);
        partial void OnAttachmentsChanged();

        #endregion

    
    }

    #endregion

    
}
